# Base Jekyll configuration

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile. There is also a
# _config.build.yml to set custom overrides for `grunt build`.

name: FromTheGeeksHead
description: A geek's blog about life and other things tech.
host : aliirz.com
url: http://aliirz.com

author:
  name: aliirz
  email: ali@sweetpixelstudios.com
  github: aliirz
  twitter: aliirz

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['images', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: pretty

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Split posts over multiple subdirectories called “page2”, “page3”, … “pageN”
paginate: 4

# Markdown library
markdown: redcarpet
# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Use Pygments to highlight code blocks
pygments: true

